# Generated by Django 5.2.1 on 2025-05-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('company_category', models.CharField(max_length=100, verbose_name='Категория компании')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company_images', verbose_name='Аватарка компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предложения')),
                ('small_name', models.CharField(max_length=100, verbose_name='Название предложения (продолжение)')),
                ('how_to_get', models.TextField(blank=True, null=True, verbose_name='Как получить')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О партнере')),
                ('start_date', models.DateField(verbose_name='Стартовая дата')),
                ('end_date', models.DateField(verbose_name='Конечная дата')),
                ('address', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('bonus_code', models.CharField(max_length=100, verbose_name='Промокод')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images', verbose_name='Изображение карточки')),
                ('cities', models.ManyToManyField(related_name='discount_cards', to='discounts_app.city', verbose_name='Города')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_cards', to='discounts_app.company', verbose_name='Компания')),
                ('categories', models.ManyToManyField(related_name='discount_cards', to='discounts_app.discountcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
