# Generated by Django 5.2.1 on 2025-05-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_category',
        ),
    ]
