# Generated by Django 5.2.1 on 2025-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0002_remove_company_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='discountcard',
            name='bonus_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Промокод'),
        ),
    ]
