# Generated by Django 5.2.1 on 2025-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0003_discountcategory_image_alter_discountcard_bonus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='offers_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория предложения'),
        ),
    ]
