# Generated by Django 5.2.1 on 2025-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0004_discountcard_offers_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts_images', verbose_name='Изображение карточки'),
        ),
    ]
