# Generated by Django 5.2.1 on 2025-05-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_app', '0005_alter_discountcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcard',
            name='bonus_code',
        ),
    ]
